ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS channels TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS campaigns TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS opt_in_whatsapp BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS opt_out_call BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS upload_batches (
  id UUID PRIMARY KEY,
  upload_type TEXT NOT NULL,
  campaign_name TEXT NOT NULL,
  total_rows INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
